# Generated by Django 2.1.5 on 2026-02-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20260210_0259'),
        ('rango', '0003_auto_20260212_2326'),
    ]

    operations = [
    ]
